"""initial migration with kakao login

Revision ID: abc123def456
Revises:
Create Date: 2025-09-29 15:00:00.000000

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "abc123def456"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("kakao_id", sa.BigInteger(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_account_email"), "user_account", ["email"], unique=True
    )
    op.create_index(
        op.f("ix_user_account_kakao_id"), "user_account", ["kakao_id"], unique=True
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("refresh_token", sa.String(length=512), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("exp", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_refresh_token"),
        "refresh_token",
        ["refresh_token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_refresh_token"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_index(op.f("ix_user_account_kakao_id"), table_name="user_account")
    op.drop_index(op.f("ix_user_account_email"), table_name="user_account")
    op.drop_table("user_account")
    # ### end Alembic commands ###
