"""add_rating_keyword_type_enum_simple

Revision ID: 1e306a85a103
Revises: 51c740e272f3
Create Date: 2025-10-03 13:59:20.695130

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "1e306a85a103"
down_revision = "51c740e272f3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. rating_keyword_type_enum 생성
    op.execute("""
        CREATE TYPE rating_keyword_type_enum AS ENUM ('positive', 'negative');
    """)

    # 2. rating_keyword_master.type 컬럼을 enum으로 변경
    op.execute("""
        ALTER TABLE rating_keyword_master
        ALTER COLUMN type TYPE rating_keyword_type_enum
        USING type::rating_keyword_type_enum;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. rating_keyword_master.type 컬럼을 text로 되돌리기
    op.execute("""
        ALTER TABLE rating_keyword_master
        ALTER COLUMN type TYPE text;
    """)

    # 2. rating_keyword_type_enum 삭제
    op.execute("""
        DROP TYPE rating_keyword_type_enum;
    """)

    # ### end Alembic commands ###
