"""add_nickname_and_profile_image_url_to_user

Revision ID: b5ace4cae445
Revises: 09af81d145b9
Create Date: 2025-10-01 10:26:27.270572

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b5ace4cae445"
down_revision = "09af81d145b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user", sa.Column("nickname", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "app_user", sa.Column("profile_image_url", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_user", "profile_image_url")
    op.drop_column("app_user", "nickname")
    # ### end Alembic commands ###
