"""migrate_wish_spots_to_postgis

Revision ID: 3c0a75ee406e
Revises: 2cf693fb8e85
Create Date: 2025-10-01 14:51:07.487071

"""

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "3c0a75ee406e"
down_revision = "2cf693fb8e85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_wish_spot",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column(
            "location",
            geoalchemy2.types.Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # GiST 인덱스 수동 생성
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_user_wish_spot_location "
        "ON user_wish_spot USING gist (location)"
    )
    op.create_index(
        op.f("ix_user_wish_spot_user_id"), "user_wish_spot", ["user_id"], unique=False
    )
    # spatial_ref_sys는 PostGIS 시스템 테이블이므로 삭제하지 않음
    op.drop_column("app_user", "wish_spots")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_user",
        sa.Column(
            "wish_spots",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # spatial_ref_sys는 PostGIS 시스템 테이블이므로 재생성하지 않음
    op.drop_index(op.f("ix_user_wish_spot_user_id"), table_name="user_wish_spot")
    op.execute("DROP INDEX IF EXISTS idx_user_wish_spot_location")
    op.drop_table("user_wish_spot")
    # ### end Alembic commands ###
