"""add_labor_fee_to_mogu_post

Revision ID: 68ef1f9d0cce
Revises: e6576188d588
Create Date: 2025-10-06 00:59:03.572886

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "68ef1f9d0cce"
down_revision = "e6576188d588"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mogu_post",
        sa.Column("labor_fee", sa.BigInteger(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mogu_post", "labor_fee")
    # ### end Alembic commands ###
