"""rename image_url to image_path in mogu_post_image

Revision ID: d05d5589df17
Revises: 68ef1f9d0cce
Create Date: 2025-10-07 00:31:14.176996

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d05d5589df17"
down_revision = "68ef1f9d0cce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # MoguPostImage 테이블의 image_url을 image_path로 변경
    op.add_column("mogu_post_image", sa.Column("image_path", sa.Text(), nullable=True))

    # 기존 데이터를 image_url에서 image_path로 복사
    op.execute(
        "UPDATE mogu_post_image SET image_path = image_url WHERE image_path IS NULL"
    )

    # image_path를 NOT NULL로 변경
    op.alter_column("mogu_post_image", "image_path", nullable=False)

    # image_url 컬럼 삭제
    op.drop_column("mogu_post_image", "image_url")

    # User 테이블의 profile_image_url을 profile_image_path로 변경
    op.add_column("app_user", sa.Column("profile_image_path", sa.Text(), nullable=True))

    # 기존 데이터를 profile_image_url에서 profile_image_path로 복사
    op.execute(
        "UPDATE app_user SET profile_image_path = profile_image_url WHERE profile_image_path IS NULL"
    )

    # profile_image_url 컬럼 삭제
    op.drop_column("app_user", "profile_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # User 테이블 복원
    op.add_column("app_user", sa.Column("profile_image_url", sa.TEXT(), nullable=True))
    op.execute(
        "UPDATE app_user SET profile_image_url = profile_image_path WHERE profile_image_path IS NOT NULL"
    )
    op.drop_column("app_user", "profile_image_path")

    # MoguPostImage 테이블 복원
    op.add_column(
        "mogu_post_image",
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.execute(
        "UPDATE mogu_post_image SET image_url = image_path WHERE image_path IS NOT NULL"
    )
    op.drop_column("mogu_post_image", "image_path")
    # ### end Alembic commands ###
