"""change user id from uuid to string

Revision ID: 09af81d145b9
Revises: 2045a2f45e4a
Create Date: 2025-09-29 22:46:37.945175

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "09af81d145b9"
down_revision = "2045a2f45e4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # UUID 컬럼을 VARCHAR로 변경
    op.alter_column("app_user", "id", type_=sa.String(36))

    op.drop_index(op.f("ix_user_account_email"), table_name="app_user")
    op.drop_index(op.f("ix_user_account_kakao_id"), table_name="app_user")
    op.create_index(op.f("ix_app_user_email"), "app_user", ["email"], unique=True)
    op.create_index(op.f("ix_app_user_kakao_id"), "app_user", ["kakao_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_app_user_kakao_id"), table_name="app_user")
    op.drop_index(op.f("ix_app_user_email"), table_name="app_user")
    op.create_index(
        op.f("ix_user_account_kakao_id"), "app_user", ["kakao_id"], unique=True
    )
    op.create_index(op.f("ix_user_account_email"), "app_user", ["email"], unique=True)

    # VARCHAR를 UUID로 되돌리기
    op.alter_column("app_user", "id", type_=sa.Uuid(as_uuid=False))
    # ### end Alembic commands ###
